//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySchedule.SecretFetcher.Secret
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Products = new HashSet<Product>();
            this.ProductLinks = new HashSet<ProductLink>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryTypeId { get; set; }
        public string Link { get; set; }
    
        public virtual CategoryType CategoryType { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ProductLink> ProductLinks { get; set; }
    }
}
