//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySchedule.SecretFetcher.Secret
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Carbohydrates { get; set; }
        public double Fats { get; set; }
        public double Proteins { get; set; }
        public double Calories { get; set; }
        public Nullable<double> PortionSize { get; set; }
        public Nullable<double> PortionAmount { get; set; }
        public int CategoryId { get; set; }
        public int ProductLinkId { get; set; }
        public string PortionName { get; set; }
        public bool IsTransported { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
