//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySchedule.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsulinUsage
    {
        public int Id { get; set; }
        public double Value { get; set; }
        public int InsulinTypeId { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual InsulinType InsulinType { get; set; }
    }
}
