//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySchedule.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsulinType
    {
        public InsulinType()
        {
            this.InsulinUsages = new HashSet<InsulinUsage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<InsulinUsage> InsulinUsages { get; set; }
    }
}
