//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySchedule.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalItem
    {
        public JournalItem()
        {
            this.Portions = new HashSet<Portion>();
        }
    
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public double Value { get; set; }
        public int JournalItemTypeId { get; set; }
        public Nullable<int> FoodUsageTypeId { get; set; }
        public Nullable<int> InsulinTypeId { get; set; }
    
        public virtual FoodUsageType FoodUsageType { get; set; }
        public virtual InsulinType InsulinType { get; set; }
        public virtual JournalItemType JournalItemType { get; set; }
        public virtual ICollection<Portion> Portions { get; set; }
    }
}
