//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySchedule.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Portions = new HashSet<Portion>();
            this.UnitProducts = new HashSet<UnitProduct>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public double Carbohydrates { get; set; }
        public double Fats { get; set; }
        public double Proteins { get; set; }
        public double Calories { get; set; }
        public string MeasurementUnit { get; set; }
        public double Size { get; set; }
        public int DefaultUnitId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Portion> Portions { get; set; }
        public virtual Unit DefaultUnit { get; set; }
        public virtual ICollection<UnitProduct> UnitProducts { get; set; }
    }
}
