//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySchedule.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Portions = new HashSet<Portion>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public int ProductTypeId { get; set; }
        public int MeasurmentTypeId { get; set; }
        public double AmountPerOne { get; set; }
        public double ValuePerOne { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual MeasurmentType MeasurmentType { get; set; }
        public virtual ICollection<Portion> Portions { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
