//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySchedule.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.Portions = new HashSet<Portion>();
            this.Products = new HashSet<Product>();
            this.UnitProducts = new HashSet<UnitProduct>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
    
        public virtual ICollection<Portion> Portions { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<UnitProduct> UnitProducts { get; set; }
    }
}
