//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySchedule.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitProduct
    {
        public int UnitId { get; set; }
        public int ProductId { get; set; }
        public double SizeCoef { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
